import { createFileRoute, Link } from '@tanstack/react-router'
import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BadgeCheck, BellRing, CircleDollarSign, LockKeyhole, Play, Sparkles, Users } from 'lucide-react'
import { clubApi, type ClubCreator, type ClubPost } from '@/lib/api'

export const Route = createFileRoute('/club')({
  head: () => ({
    meta: [
      { title: 'TheSex Club · Conteúdo exclusivo' },
      { name: 'description', content: 'Conheça canais exclusivos, acompanhe publicações abertas e descubra o TheSex Club.' },
      { name: 'robots', content: 'index,follow' },
    ],
  }),
  component: ClubPage,
})

function ClubPage() {
  const [creators, setCreators] = useState<ClubCreator[]>([])
  const [posts, setPosts] = useState<ClubPost[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.all([clubApi.creators(), clubApi.feed()])
      .then(([nextCreators, nextPosts]) => { setCreators(nextCreators); setPosts(nextPosts) })
      .finally(() => setLoading(false))
  }, [])

  const highlighted = useMemo(() => creators.slice(0, 6), [creators])
  return <main className="min-h-dvh bg-[#120d16] text-white">
    <header className="border-b border-white/10 bg-[#120d16]/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><Link to="/" className="text-xl font-black tracking-tight text-fuchsia-400">the<span className="text-white">sex</span><span className="ml-1 text-xs text-fuchsia-200">club</span></Link><nav className="hidden items-center gap-6 text-sm font-bold text-slate-300 md:flex"><a href="#canais" className="hover:text-white">Canais</a><a href="#feed" className="hover:text-white">Feed aberto</a><Link to="/explore" search={{ q: '', city: '', category: '' }} className="hover:text-white">Perfis</Link></nav><Link to="/member" className="rounded-xl bg-white px-4 py-2.5 text-sm font-black text-fuchsia-700 transition hover:bg-fuchsia-50">Criar meu canal</Link></div></header>

    <section className="relative isolate overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_15%,rgba(236,72,153,.42),transparent_25%),radial-gradient(circle_at_82%_72%,rgba(124,58,237,.45),transparent_31%)]"/><div className="relative mx-auto grid max-w-7xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:items-end lg:py-28"><div><p className="inline-flex items-center gap-2 rounded-full border border-fuchsia-300/30 bg-fuchsia-400/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] text-fuchsia-100"><Sparkles className="h-3.5 w-3.5"/>TheSex Club</p><h1 className="mt-6 max-w-3xl text-4xl font-black leading-[.96] tracking-tight sm:text-6xl">Uma área exclusiva, ligada a perfis reais.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">Canais passam por análise, mantêm identidade vinculada ao perfil e publicam conteúdo sob as regras da plataforma.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#canais" className="inline-flex items-center gap-2 rounded-xl bg-fuchsia-500 px-5 py-3 text-sm font-black text-white shadow-lg shadow-fuchsia-900/40 hover:bg-fuchsia-400">Explorar canais<ArrowRight className="h-4 w-4"/></a><Link to="/member" className="inline-flex items-center gap-2 rounded-xl border border-white/20 px-5 py-3 text-sm font-black text-white hover:bg-white/10"><Play className="h-4 w-4"/>Publicar no Club</Link></div></div><aside className="rounded-3xl border border-white/10 bg-white/[.07] p-6 shadow-2xl shadow-black/20 backdrop-blur"><BadgeCheck className="h-7 w-7 text-fuchsia-300"/><h2 className="mt-5 text-xl font-black">Estrutura feita para crescer</h2><div className="mt-6 grid gap-3"><Feature icon={Users} title="Canais vinculados" text="A origem de cada canal é um perfil aprovado."/><Feature icon={LockKeyhole} title="Conteúdo protegido" text="Área exclusiva preparada para assinaturas e PPV."/><Feature icon={CircleDollarSign} title="Operação auditável" text="Pedidos, eventos e moderação centralizados."/></div></aside></div></section>

    <section id="canais" className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-300">Canais em destaque</p><h2 className="mt-2 text-3xl font-black">Quem já está no Club</h2></div><p className="max-w-md text-sm leading-6 text-slate-400">Canais novos só ficam públicos depois da aprovação da equipe.</p></div>{loading ? <LoadingGrid/> : highlighted.length === 0 ? <EmptyClub/> : <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{highlighted.map(creator => <CreatorCard key={creator.id} creator={creator}/>)}</div>}</section>

    <section id="feed" className="border-y border-white/10 bg-white/[.035]"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-300">Feed aberto</p><h2 className="mt-2 text-3xl font-black">Amostras publicadas</h2></div><BellRing className="h-6 w-6 text-fuchsia-300"/></div>{loading ? <LoadingGrid/> : posts.length === 0 ? <div className="mt-8 rounded-3xl border border-dashed border-white/15 bg-white/[.03] p-10 text-center text-sm text-slate-400">As primeiras publicações abertas aparecerão aqui após a moderação.</div> : <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{posts.map(post => <PostCard key={post.id} post={post}/>)}</div>}</div></section>

    <footer className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-10 text-sm text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:px-6"><p><strong className="text-white">TheSex Club</strong> · Área exclusiva para maiores de 18 anos.</p><div className="flex gap-5"><Link to="/" className="hover:text-white">Voltar ao TheSex</Link><Link to="/member" className="font-bold text-fuchsia-300 hover:text-fuchsia-200">Área de membro</Link></div></footer>
  </main>
}

function Feature({ icon: Icon, title, text }: { icon: typeof Users; title: string; text: string }) { return <div className="flex gap-3 rounded-2xl border border-white/10 bg-black/10 p-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-fuchsia-400/10 text-fuchsia-200"><Icon className="h-4 w-4"/></span><div><p className="text-sm font-black">{title}</p><p className="mt-0.5 text-xs leading-5 text-slate-400">{text}</p></div></div> }
function CreatorCard({ creator }: { creator: ClubCreator }) { const price = creator.monthly_price_cents > 0 ? `R$ ${(creator.monthly_price_cents / 100).toFixed(2).replace('.', ',')}/mês` : 'Acompanhe o canal'; return <a href={`/club/${creator.username}`} onClick={() => void clubApi.track('creator_viewed', creator.id)} className="group overflow-hidden rounded-3xl border border-white/10 bg-white/[.055] transition hover:-translate-y-1 hover:border-fuchsia-400/50 hover:bg-white/[.08]"><div className="relative aspect-[16/10] overflow-hidden bg-gradient-to-br from-fuchsia-700 via-violet-800 to-slate-950">{creator.cover_photo ? <img src={creator.cover_photo} alt="" className="h-full w-full object-cover opacity-80 transition duration-500 group-hover:scale-105 group-hover:opacity-100"/> : <div className="absolute inset-0 bg-[radial-gradient(circle_at_74%_24%,rgba(255,255,255,.25),transparent_10%),linear-gradient(120deg,transparent,rgba(255,255,255,.08))]"/>}<span className="absolute left-4 top-4 rounded-full bg-black/45 px-2.5 py-1 text-[10px] font-black uppercase tracking-wider text-white backdrop-blur">Canal verificado</span></div><div className="p-5"><p className="text-lg font-black">{creator.display_name}</p><p className="mt-1 line-clamp-2 min-h-10 text-sm leading-5 text-slate-400">{creator.bio || 'Canal exclusivo vinculado a perfil aprovado.'}</p><div className="mt-5 flex items-center justify-between"><span className="text-xs font-black text-fuchsia-200">{price}</span><span className="inline-flex items-center gap-1 text-sm font-black text-white">Abrir<ArrowRight className="h-4 w-4"/></span></div></div></a> }
function PostCard({ post }: { post: ClubPost }) { const image = post.media[0]; return <article className="overflow-hidden rounded-3xl border border-white/10 bg-[#1b1520]"><div className="relative aspect-[4/3] overflow-hidden bg-gradient-to-br from-fuchsia-900/70 via-violet-950 to-slate-950">{image ? <img src={image} alt="" loading="lazy" className="h-full w-full object-cover transition duration-500 hover:scale-105"/> : <div className="flex h-full items-center justify-center"><LockKeyhole className="h-8 w-8 text-white/40"/></div>}{post.media.length > 1 && <span className="absolute bottom-3 right-3 rounded-full bg-black/60 px-2 py-1 text-xs font-black">+{post.media.length - 1}</span>}</div><div className="p-5"><p className="text-xs font-black uppercase tracking-[.15em] text-fuchsia-300">{post.creator_name || post.creator_username}</p><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-300">{post.caption}</p><button onClick={() => void clubApi.track(post.visibility === 'ppv' ? 'ppv_intent' : 'post_opened', post.creator_id, post.id)} className="mt-4 text-xs font-black text-white hover:text-fuchsia-200">Ver publicação <ArrowRight className="inline h-3.5 w-3.5"/></button></div></article> }
function LoadingGrid() { return <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-72 animate-pulse rounded-3xl bg-white/[.06]"/>)}</div> }
function EmptyClub() { return <div className="mt-8 rounded-3xl border border-dashed border-white/15 bg-white/[.03] p-10 text-center"><Users className="mx-auto h-8 w-8 text-fuchsia-300"/><h3 className="mt-4 text-lg font-black">O Club está sendo preparado</h3><p className="mt-2 text-sm leading-6 text-slate-400">Os primeiros canais aprovados aparecerão aqui. Se você já possui um perfil publicado, poderá solicitar seu canal pela área de membro.</p><Link to="/member" className="mt-5 inline-flex rounded-xl bg-white px-4 py-2.5 text-sm font-black text-fuchsia-700">Acessar área de membro</Link></div> }
