import { createFileRoute, Link as RouterLink } from '@tanstack/react-router'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { profilesApi, type Profile } from '@/lib/api'
import { SEO_REGIONS } from '@/lib/seo-regions'
import { ArrowRight, BadgeCheck, ChevronRight, MapPin, Search, ShieldCheck, Sparkles, X } from 'lucide-react'

const DISCOVER = [
  { title: 'Acompanhantes', text: 'Perfis para encontros com discrição e estilo.', tone: 'from-rose-500 to-pink-600' },
  { title: 'Massagens', text: 'Bem-estar, relaxamento e experiências personalizadas.', tone: 'from-violet-500 to-fuchsia-600' },
  { title: 'Trans e Travesti', text: 'Perfis revisados em várias cidades do Brasil.', tone: 'from-sky-500 to-indigo-600' },
  { title: 'Encontro casual', text: 'Conexões para viver bons momentos, no seu ritmo.', tone: 'from-orange-500 to-rose-500' },
]
const CITY_LINKS = ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Curitiba', 'Brasília', 'Salvador']
const CATEGORY_FILTERS: Record<string, string> = { Acompanhantes: 'Acompanhante', Massagens: 'Massagem', 'Trans e Travesti': 'Trans e Travesti', 'Encontro casual': 'Encontro casual' }

function Link(props: any) {
  if (props.to === '/profile/$id' && typeof props.params?.id === 'string' && props.params.id.startsWith('/')) {
    const { to: _to, params: _params, ...anchorProps } = props
    return <a href={_params.id} {...anchorProps} />
  }
  return <RouterLink {...props} />
}

export const Route = createFileRoute('/')({
  head: () => ({ meta: [{ title: 'Acompanhantes, Escorts e Garotas de Programa | TheSex' }, { name: 'description', content: 'Encontre acompanhantes, escorts, garotas de programa e encontros casuais na sua cidade. Perfis, fotos e contato direto.' }, { name: 'keywords', content: 'acompanhantes, escorts, garotas de programa, acompanhantes de luxo, sexo casual, encontros casuais' }] }),
  component: Home,
})

function Home() {
  const [profiles, setProfiles] = useState<Profile[]>([])
  const [loading, setLoading] = useState(true)
  const [query, setQuery] = useState('')
  const [selectedCity, setSelectedCity] = useState('')
  const loadProfiles = useCallback(async () => { try { setProfiles(await profilesApi.list()) } finally { setLoading(false) } }, [])
  useEffect(() => { void loadProfiles() }, [loadProfiles])

  const cities = useMemo(() => [...new Set([...CITY_LINKS, ...profiles.map(profile => profile.city)])], [profiles])
  const visibleProfiles = profiles.filter(profile => {
    const search = query.trim().toLowerCase()
    return (!selectedCity || profile.city === selectedCity) && (!search || [profile.name, profile.city, profile.category, profile.neighborhood, ...profile.tags].join(' ').toLowerCase().includes(search))
  })
  const featured = visibleProfiles.filter(profile => profile.is_featured)

  return <main className="min-h-dvh bg-[#fffafb] text-slate-900">
    <header className="border-b border-slate-100 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><Link to="/" className="text-xl font-black tracking-tight text-pink-600">the<span className="text-slate-900">sex</span></Link><nav className="hidden items-center gap-6 text-sm font-bold text-slate-600 md:flex"><a href="#categorias" className="hover:text-pink-600">Categorias</a><Link to="/explore" search={{ q: '', city: '', category: '' }} className="hover:text-pink-600">Perfis</Link><a href="#cidades" className="hover:text-pink-600">Cidades</a></nav><div className="flex items-center gap-3"><Link to="/member" className="hidden text-sm font-black text-slate-600 hover:text-pink-600 sm:inline-flex">Área de membro</Link><Link to="/create" className="hidden rounded-xl bg-pink-600 px-4 py-2.5 text-sm font-black text-white shadow-lg shadow-pink-600/20 hover:bg-pink-700 sm:inline-flex">Publicar perfil</Link></div></div></header>
    <div className="bg-gradient-to-r from-pink-600 to-violet-600 text-white"><div className="mx-auto flex max-w-6xl items-center justify-center gap-2 px-4 py-2 text-center text-xs font-bold sm:text-sm"><BadgeCheck className="h-4 w-4" />Perfis passam por análise antes de aparecerem na vitrine.</div></div>
    <section className="relative isolate overflow-hidden bg-[#190b20]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_30%,rgba(236,72,153,.75),transparent_23%),radial-gradient(circle_at_18%_80%,rgba(168,85,247,.55),transparent_30%)]" /><div className="relative mx-auto max-w-6xl px-4 py-20 sm:px-6 sm:py-28"><div className="max-w-3xl"><p className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-3 py-1.5 text-xs font-bold text-pink-100"><Sparkles className="h-3.5 w-3.5" />Vitrine independente</p><h1 className="mt-5 text-4xl font-black tracking-tight text-white sm:text-6xl">Encontre perfis que combinam com o seu momento.</h1><p className="mt-5 max-w-xl text-base leading-7 text-pink-100 sm:text-lg">Pesquise por cidade, categoria ou interesse. Contato direto, informações claras e publicação após revisão.</p></div><div className="mt-9 rounded-2xl bg-white p-2 shadow-2xl shadow-black/30 sm:flex sm:items-center"><div className="flex flex-1 items-center gap-3 px-3 py-2"><Search className="h-5 w-5 text-pink-600" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar por cidade, categoria ou nome..." className="w-full bg-transparent text-sm font-medium text-slate-800 outline-none placeholder:text-slate-400" />{query && <button aria-label="Limpar busca" onClick={() => setQuery('')}><X className="h-4 w-4 text-slate-400" /></button>}</div><button onClick={() => document.getElementById('perfis')?.scrollIntoView({ behavior: 'smooth' })} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-pink-600 px-6 py-3 text-sm font-black text-white hover:bg-pink-700 sm:mt-0 sm:w-auto">Encontrar perfis<ArrowRight className="h-4 w-4" /></button></div></div></section>
    <section id="categorias" className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.18em] text-pink-600">Descubra</p><h2 className="mt-2 text-3xl font-black text-slate-900">O que você procura?</h2></div><Link to="/create" className="hidden text-sm font-bold text-pink-600 hover:text-pink-700 sm:inline-flex">Cadastrar perfil<ChevronRight className="h-4 w-4" /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{DISCOVER.map((item, index) => <Link key={item.title} to="/explore" search={{ category: CATEGORY_FILTERS[item.title] ?? item.title, city: '', q: '' }} className="group overflow-hidden rounded-2xl bg-white text-left shadow-sm ring-1 ring-slate-100 transition hover:-translate-y-1 hover:shadow-xl"><div className={`h-24 bg-gradient-to-br ${item.tone} p-5 text-white`}><span className="text-xs font-black uppercase tracking-[.18em]">0{index + 1}</span></div><div className="p-5"><h3 className="text-lg font-black text-slate-900">{item.title}</h3><p className="mt-2 text-sm leading-5 text-slate-500">{item.text}</p><span className="mt-4 inline-flex text-sm font-bold text-pink-600">Explorar<ChevronRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></Link>)}</div></section>
    <section id="perfis" className="border-y border-pink-100 bg-white"><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-[.18em] text-pink-600">Em destaque</p><h2 className="mt-2 text-3xl font-black text-slate-900">Perfis publicados</h2><p className="mt-2 text-sm text-slate-500">Use os filtros para encontrar pessoas na sua cidade.</p></div><div className="flex flex-wrap gap-2">{cities.slice(0, 6).map(city => <button key={city} onClick={() => setSelectedCity(city === selectedCity ? '' : city)} className={`rounded-full border px-3 py-2 text-xs font-bold ${city === selectedCity ? 'border-pink-600 bg-pink-600 text-white' : 'border-pink-100 bg-pink-50 text-pink-700 hover:border-pink-300'}`}>{city}</button>)}</div></div>{loading ? <ProfileSkeleton /> : visibleProfiles.length === 0 ? <EmptyProfiles reset={() => { setQuery(''); setSelectedCity('') }} /> : <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[...featured, ...visibleProfiles.filter(profile => !profile.is_featured)].map(profile => <ProfileCard key={profile.id} profile={profile} />)}</div>}<div className="mt-9 text-center"><Link to="/explore" search={{ q: query, city: selectedCity, category: '' }} className="inline-flex items-center gap-2 rounded-xl border border-pink-200 bg-pink-50 px-5 py-3 text-sm font-black text-pink-700 hover:border-pink-300">Abrir catálogo completo<ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <section id="cidades" className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className="rounded-3xl bg-slate-900 p-7 text-white sm:p-10"><div className="grid gap-8 md:grid-cols-[1.3fr_.7fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-pink-300">Por cidade</p><h2 className="mt-2 text-3xl font-black">Uma vitrine organizada para encontrar com tranquilidade.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-300">Escolha sua cidade, descubra categorias e converse diretamente com perfis aprovados.</p></div><div className="grid grid-cols-2 content-center gap-2">{cities.slice(0, 6).map(city => <button key={city} onClick={() => { setSelectedCity(city); document.getElementById('perfis')?.scrollIntoView({ behavior: 'smooth' }) }} className="rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-left text-sm font-bold hover:bg-white/10"><MapPin className="mr-1 inline h-3.5 w-3.5 text-pink-300" />{city}</button>)}</div></div></div></section>
    <footer className="border-t border-pink-100 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-9 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-6"><p><strong className="text-pink-600">thesex</strong> · Perfis independentes para maiores de 18 anos.</p><div className="flex gap-5"><Link to="/create" className="font-bold text-pink-600">Cadastrar perfil</Link><a href="#categorias">Categorias</a></div></div></footer>
    <RegionSeoLinks />
  </main>
}

function RegionSeoLinks() {
  return <section className="border-t border-pink-100 bg-[#fffafb]"><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><p className="text-xs font-black uppercase tracking-[.18em] text-pink-600">Navegue por cidade</p><h2 className="mt-2 text-2xl font-black text-slate-900">Páginas locais</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Escolha uma cidade para consultar os perfis publicados naquela região e encontrar informações locais.</p><nav aria-label="Páginas locais por cidade" className="mt-5 flex flex-wrap gap-2">{SEO_REGIONS.map((region) => <a key={region.slug} href={`/${region.slug}`} className="rounded-full border border-pink-200 bg-white px-4 py-2 text-sm font-bold text-pink-700 transition hover:border-pink-500 hover:bg-pink-50">{region.title.replace('Perfis em ', '').replace('Perfis no ', '')}</a>)}</nav></div></section>
}

function ProfileCard({ profile }: { profile: Profile }) {
  const photo = profile.photos[0]
  return <Link to="/profile/$id" params={{ id: profile.id }} className="group overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden bg-gradient-to-br from-pink-100 to-violet-100">{photo ? <img src={photo} alt={profile.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-sm font-bold text-pink-400">Fotos em atualização</div>}<span className="absolute left-3 top-3 rounded-full bg-white/95 px-2.5 py-1 text-[11px] font-black text-pink-600 shadow-sm">{profile.category}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-black text-slate-900">{profile.name}, {profile.age}</h3><p className="mt-1 text-sm text-slate-500"><MapPin className="mr-1 inline h-3.5 w-3.5 text-pink-500" />{profile.city}{profile.neighborhood ? ` · ${profile.neighborhood}` : ''}</p></div><span className="rounded-lg bg-pink-50 px-2 py-1 text-xs font-black text-pink-700">{profile.price}</span></div><div className="mt-4 flex flex-wrap gap-1.5">{profile.tags.slice(0, 3).map(tag => <span key={tag} className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-500">{tag}</span>)}</div><p className="mt-4 text-sm font-bold text-pink-600">Ver perfil<ArrowRight className="inline h-4 w-4" /></p></div></Link>
}

function EmptyProfiles({ reset }: { reset: () => void }) { return <div className="mt-8 rounded-3xl border border-dashed border-pink-200 bg-pink-50 p-12 text-center"><Search className="mx-auto h-9 w-9 text-pink-300" /><h3 className="mt-4 text-lg font-black text-slate-800">Ainda não há perfis para este filtro</h3><p className="mt-2 text-sm text-slate-500">Novos cadastros aprovados aparecerão aqui.</p><button onClick={reset} className="mt-5 rounded-xl border border-pink-200 bg-white px-4 py-2 text-sm font-bold text-pink-600">Limpar filtros</button></div> }
function ProfileSkeleton() { return <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="overflow-hidden rounded-2xl border border-slate-100"><div className="aspect-[4/3] animate-pulse bg-pink-100" /><div className="space-y-3 p-5"><div className="h-5 w-36 animate-pulse rounded bg-slate-100" /><div className="h-4 w-24 animate-pulse rounded bg-slate-100" /></div></div>)}</div> }
