/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/member'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ClubRouteImport } from './routes/club'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RegionRouteImport } from './routes/$region'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ClubUsernameRouteImport } from './routes/club.$username'
import { Route as CategoryCityProfileRouteImport } from './routes/$category/$city/$profile'

const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubUsernameRoute = ClubUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ClubRoute,
} as any)
const CategoryCityProfileRoute = CategoryCityProfileRouteImport.update({
  id: '/$category/$city/$profile',
  path: '/$category/$city/$profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region': typeof RegionRoute
  '/admin': typeof AdminRoute
  '/club': typeof ClubRouteWithChildren
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/member': typeof MemberRoute
  '/club/$username': typeof ClubUsernameRoute
  '/profile/$id': typeof ProfileIdRoute
  '/$category/$city/$profile': typeof CategoryCityProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$region': typeof RegionRoute
  '/admin': typeof AdminRoute
  '/club': typeof ClubRouteWithChildren
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/member': typeof MemberRoute
  '/club/$username': typeof ClubUsernameRoute
  '/profile/$id': typeof ProfileIdRoute
  '/$category/$city/$profile': typeof CategoryCityProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region': typeof RegionRoute
  '/admin': typeof AdminRoute
  '/club': typeof ClubRouteWithChildren
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/member': typeof MemberRoute
  '/club/$username': typeof ClubUsernameRoute
  '/profile/$id': typeof ProfileIdRoute
  '/$category/$city/$profile': typeof CategoryCityProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region'
    | '/admin'
    | '/club'
    | '/create'
    | '/explore'
    | '/member'
    | '/club/$username'
    | '/profile/$id'
    | '/$category/$city/$profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$region'
    | '/admin'
    | '/club'
    | '/create'
    | '/explore'
    | '/member'
    | '/club/$username'
    | '/profile/$id'
    | '/$category/$city/$profile'
  id:
    | '__root__'
    | '/'
    | '/$region'
    | '/admin'
    | '/club'
    | '/create'
    | '/explore'
    | '/member'
    | '/club/$username'
    | '/profile/$id'
    | '/$category/$city/$profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionRoute: typeof RegionRoute
  AdminRoute: typeof AdminRoute
  ClubRoute: typeof ClubRouteWithChildren
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  MemberRoute: typeof MemberRoute
  ProfileIdRoute: typeof ProfileIdRoute
  CategoryCityProfileRoute: typeof CategoryCityProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region': {
      id: '/$region'
      path: '/$region'
      fullPath: '/$region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$username': {
      id: '/club/$username'
      path: '/$username'
      fullPath: '/club/$username'
      preLoaderRoute: typeof ClubUsernameRouteImport
      parentRoute: typeof ClubRoute
    }
    '/$category/$city/$profile': {
      id: '/$category/$city/$profile'
      path: '/$category/$city/$profile'
      fullPath: '/$category/$city/$profile'
      preLoaderRoute: typeof CategoryCityProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClubRouteChildren {
  ClubUsernameRoute: typeof ClubUsernameRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubUsernameRoute: ClubUsernameRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionRoute: RegionRoute,
  AdminRoute: AdminRoute,
  ClubRoute: ClubRouteWithChildren,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  MemberRoute: MemberRoute,
  ProfileIdRoute: ProfileIdRoute,
  CategoryCityProfileRoute: CategoryCityProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
